name: NETWORK AND CLOUD LABORATORY - Interview score system auto deployment pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Create env file'
        run: |
          touch .env
          echo MONGO_CONNECTION_STRING=${{ secrets.MONGO_CONNECTION_STRING }} >> .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo MONGO_DB_NAME=${{ secrets.MONGO_DB_NAME }} >> .env
          echo "Environment variables created successfully : "
          cat .env

      - name: Remove old Docker container
        run: |
          docker rm -f nwl-interview-scoring-api || true
          
      - name: Build Docker image
        run: |
          docker build -t api-image .

      - name: Run Docker container
        run: |
          docker run -d \
          --name nwl-interview-scoring-api \
          --network host \
          -p 6970:${{ secrets.PORT }} \
          api-image
